# Generated by Django 5.1.1 on 2024-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_contact_number_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
