# Generated by Django 5.1.1 on 2024-10-19 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_customuser_alter_rating_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='rating',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
