# Generated by Django 5.1.1 on 2024-10-19 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_customuser_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='key_skills',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professional_experience',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professional_summary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_contacts',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
