# Generated by Django 5.1.1 on 2024-10-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_contact_number_user_field_of_work_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
