# Generated by Django 5.1.1 on 2024-10-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_customuser_groups_remove_customuser_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ratings',
        ),
    ]
