# Generated by Django 5.1.1 on 2024-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
