# Generated by Django 5.1.3 on 2024-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
