# Generated by Django 5.1.1 on 2024-10-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=100),
            preserve_default=False,
        ),
    ]
