# Generated by Django 5.1.1 on 2024-11-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('cleaning_services', 'Cleaning Services'), ('massage', 'Massage'), ('childcare_services', 'Childcare Services'), ('carpentry', 'Carpentry'), ('other', 'Other')], default='Plumber', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit_debit', 'Credit/Debit')], default='Cash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('internship', 'Internship'), ('project_work', 'Project Work'), ('volunteering', 'Volunteering')], default='One-Time', max_length=50),
            preserve_default=False,
        ),
    ]
