# Generated by Django 5.1.1 on 2024-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('cleaning_services', 'Cleaning Services'), ('massage', 'Massage'), ('childcare_services', 'Childcare Services'), ('carpentry', 'Carpentry'), ('other', 'Other')], default='none', max_length=50),
        ),
    ]
