# Generated by Django 5.1.1 on 2024-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
