# Generated by Django 5.1.1 on 2024-10-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
