# Generated by Django 5.1.2 on 2024-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_category_job_payment_method_job_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'Gcash'), ('credit_debit', 'Credit/Debit')], default='cash', max_length=20),
        ),
    ]
