# Generated by Django 5.1.2 on 2024-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_category_alter_job_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('cleaning_services', 'Cleaning Services'), ('massage', 'Massage'), ('childcare_services', 'Childcare Services'), ('carpentry', 'Carpentry'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit_debit', 'Credit/Debit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('within_a_week', 'Within a Week'), ('flexible', 'Flexible')], max_length=50),
        ),
    ]
